name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Deploy to EC2
      env:
        EC2_ACTIONS_SSH_KEY: ${{ secrets.EC2_ACTIONS_SSH_KEY }}
        HOST: '16.170.224.150'
      run: |
        # Install SSH client
        sudo apt-get update
        sudo apt-get install openssh-client -y
    
        # Start SSH agent
        eval $(ssh-agent -s)
    
        # Add private key to the agent
        ssh-add - <<< "${EC2_ACTIONS_SSH_KEY}"
    
        # Create SSH directory and configure
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "StrictHostKeyChecking no" > ~/.ssh/config
        chmod 644 ~/.ssh/config
    
        # Copy the entire current directory to the remote server
        scp -r . ec2-user@${{ HOST }}:/var/www/app

        # Deploy the application
        ssh ec2-user@$HOST 'cd /var/www/app && npm install && pm2 reload all --update-env'
